[tool.poetry]
name = "insanonym-utils"
version = "0.1.0"
description = ""
authors = ["Daniel Mathiot <d.danymat@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

