
name: "Publish docs"
on: 
  push:
    branches:
      - main
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9.4]
        poetry-version: [1.1.6]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
         poetry install
      - name: Build docs
        run: |
          mkdir -p .deploy
          poetry run pdoc --html insanonym_utils --force -o .deploy
          mv .deploy/insanonym_utils .deploy/docs
          cp -R docs/* .deploy/docs
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
